# Generated by Django 4.1.1 on 2022-09-12 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripeapi", "0003_alter_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(50)]
            ),
        ),
    ]
